version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
#    time: "21:00"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  # Overwrite any ignores created using `@dependabot ignore` commands
  ignore:
    # Ignore updates to packages that start 'aws'
    # Wildcards match zero or more arbitrary characters
    #- dependency-name: "aws*"
    # Ignore some updates to the 'resteasy' package
    - dependency-name: "resteasy"
      # Ignore only new versions for 4.x
      versions: ["3.x, 4.x"]
    - dependency-name: "jakarta.jakartaee-api"
    - dependency-name: "glassfish"
    - dependency-name: "jersey"
    - dependency-name: "eclipselink"
    - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
      
      
          
